/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates a new user account. Returns access_token in body (store in JS memory). Sets refresh_token as HttpOnly cookie (server-managed, client never reads it).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterInput"];
                };
            };
            responses: {
                /** @description Registration successful. access_token in body. refresh_token set as HttpOnly cookie by server. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Email already registered */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email and password
         * @description Authenticates a user. Returns access_token in body (store in JS memory). Sets refresh_token as HttpOnly cookie (server-managed, client never reads it).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginInput"];
                };
            };
            responses: {
                /** @description Login successful. access_token in body. refresh_token set as HttpOnly cookie by server. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get a new access token
         * @description No request body. The HttpOnly refresh token cookie is sent automatically by the browser or native cookie handler. Server validates the refresh token against the DB, issues a new access_token in the response body, and rotates the refresh_token cookie (new cookie set, old one invalidated). Client stores the new access_token in memory. Call this proactively when the access token is within 5 minutes of expiry (check the exp claim in the JWT payload) to avoid 401 roundtrips.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description New access_token in body. Refresh token cookie also rotated by server. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RefreshResponse"];
                    };
                };
                /** @description Refresh token cookie missing, expired, or revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out and invalidate the refresh token
         * @description No request body. The HttpOnly refresh token cookie is sent automatically. Server deletes the refresh token from DB (revokes it) and clears the cookie. Client must also clear the access token from memory.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out. Cookie cleared. Clear access token from memory. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No valid refresh token cookie */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kana": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all kana characters */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (1-indexed) */
                    page?: components["parameters"]["PageParam"];
                    /** @description Number of results per page */
                    page_size?: components["parameters"]["PageSizeParam"];
                    /** @description Filter by hiragana or katakana */
                    type?: "hiragana" | "katakana";
                    /** @description Filter by kana category */
                    category?: "base" | "dakuten" | "handakuten" | "yoon";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of kana */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedKana"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kana/{character}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single kana character */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example き */
                    character: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Kana character detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Kana"];
                    };
                };
                /** @description Character not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kanji": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List kanji characters
         * @description Public endpoint. No auth required. Does not include components or sentences.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (1-indexed) */
                    page?: components["parameters"]["PageParam"];
                    /** @description Number of results per page */
                    page_size?: components["parameters"]["PageSizeParam"];
                    /** @description Optional. Filter to exactly this JLPT level. Mutually exclusive with jlpt_max — providing both is a 422. */
                    jlpt?: components["parameters"]["JlptParam"];
                    /** @description Optional. Filter to this JLPT level or easier (e.g. N3 includes N3, N4, and N5; NULL-jlpt items are excluded). Mutually exclusive with jlpt — providing both is a 422. */
                    jlpt_max?: components["parameters"]["JlptMaxParam"];
                    /** @description Filter by Japanese school grade */
                    grade?: number;
                    /** @description Filter by number of strokes */
                    stroke_count?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of kanji */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedKanji"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kanji/{character}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single kanji with full detail
         * @description Requires auth. Returns the kanji with its components, up to 10 JLPT-ordered example sentences, up to 20 vocab words grouped by reading type, classical radical info, and the user's mnemonic override. user_mnemonic is null if the user has not set one — display mnemonic (the LLM default) instead.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 新 */
                    character: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Kanji detail with components, sentences, and user_mnemonic */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Kanji"];
                    };
                };
                /** @description Missing or expired access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Kanji not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kanji/{character}/mnemonic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set or clear the user's personal mnemonic for a kanji
         * @description Requires auth. Send the mnemonic string to set it. Send empty string "" to clear it and revert to the LLM default (mnemonic field on kanji).
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 新 */
                    character: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MnemonicUpdateInput"];
                };
            };
            responses: {
                /** @description Mnemonic updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MnemonicUpdateResponse"];
                    };
                };
                /** @description Missing or expired access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Kanji not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/kanji/practice-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a random batch of kanji for a Practice tab session
         * @description Requires auth (Practice tab requires login). Returns a stateless, ready-to-play batch — no session is stored server-side. Each kanji includes distractor_meanings for MCQ-style games.
         */
        get: {
            parameters: {
                query: {
                    /** @description The JLPT level this practice session is centered on. */
                    jlpt_level: components["parameters"]["PracticeJlptLevelParam"];
                    /** @description "exact" — only jlpt_level. "and_below" — jlpt_level and every easier level (N5 is the floor, so N5 + and_below = N5 only). */
                    scope: components["parameters"]["PracticeScopeParam"];
                    /** @description "balanced" — as even a split as possible across every level in range. "challenge" — skewed toward the harder level(s) in range. */
                    distribution: components["parameters"]["PracticeDistributionParam"];
                    /** @description Number of items requested. The actual number returned may be lower if a level in range doesn't have enough rows (after exclude) to fill its share. */
                    count?: components["parameters"]["PracticeCountParam"];
                    /** @description Comma-separated list of identifiers (kanji characters, vocab ids, depending on the endpoint) already seen this session, so a top-up call doesn't reintroduce duplicates. */
                    exclude?: components["parameters"]["PracticeExcludeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A batch of kanji for practice */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PracticeBatchKanji"];
                    };
                };
                /** @description Missing or expired access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/mnemonics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the authenticated user's custom kanji mnemonics
         * @description Requires auth. Returns only kanji for which the user has written a mnemonic override (via PATCH /kanji/{character}/mnemonic) — not every kanji. Ordered by updated_at descending (most recently edited first).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (1-indexed) */
                    page?: components["parameters"]["PageParam"];
                    /** @description Number of results per page */
                    page_size?: components["parameters"]["PageSizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of the user's custom mnemonics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedUserMnemonic"];
                    };
                };
                /** @description Missing or expired access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List vocabulary words
         * @description Public endpoint. No auth required.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (1-indexed) */
                    page?: components["parameters"]["PageParam"];
                    /** @description Number of results per page */
                    page_size?: components["parameters"]["PageSizeParam"];
                    /** @description Optional. Filter to exactly this JLPT level. Mutually exclusive with jlpt_max — providing both is a 422. */
                    jlpt?: components["parameters"]["JlptParam"];
                    /** @description Optional. Filter to this JLPT level or easier (e.g. N3 includes N3, N4, and N5; NULL-jlpt items are excluded). Mutually exclusive with jlpt — providing both is a 422. */
                    jlpt_max?: components["parameters"]["JlptMaxParam"];
                    /** @description Filter to common words only (ichi1/news1/spec1 tagged) */
                    is_common?: boolean;
                    /** @description Search by word or reading (partial match) */
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of vocabulary words */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedVocab"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocab/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single vocabulary word with example sentences
         * @description Public endpoint. No auth required.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description JMdict entry sequence number
                     * @example 1578850
                     */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vocabulary word detail with example sentences */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vocab"];
                    };
                };
                /** @description Vocab entry not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocab/practice-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a random batch of vocabulary words for a Practice tab session
         * @description Requires auth (Practice tab requires login). Returns a stateless, ready-to-play batch — no session is stored server-side. Each word includes distractor_meanings for MCQ-style games.
         */
        get: {
            parameters: {
                query: {
                    /** @description The JLPT level this practice session is centered on. */
                    jlpt_level: components["parameters"]["PracticeJlptLevelParam"];
                    /** @description "exact" — only jlpt_level. "and_below" — jlpt_level and every easier level (N5 is the floor, so N5 + and_below = N5 only). */
                    scope: components["parameters"]["PracticeScopeParam"];
                    /** @description "balanced" — as even a split as possible across every level in range. "challenge" — skewed toward the harder level(s) in range. */
                    distribution: components["parameters"]["PracticeDistributionParam"];
                    /** @description Number of items requested. The actual number returned may be lower if a level in range doesn't have enough rows (after exclude) to fill its share. */
                    count?: components["parameters"]["PracticeCountParam"];
                    /** @description Comma-separated list of identifiers (kanji characters, vocab ids, depending on the endpoint) already seen this session, so a top-up call doesn't reintroduce duplicates. */
                    exclude?: components["parameters"]["PracticeExcludeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A batch of vocabulary words for practice */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PracticeBatchVocab"];
                    };
                };
                /** @description Missing or expired access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocab/crossword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an interlocking vocab crossword for a Practice tab session
         * @description Requires auth (Practice tab requires login). Generates a solved, interlocking crossword grid from vocab words at the requested JLPT filter — hiragana and katakana mixed, no count/type balance requirement. The number of words that fit is determined by the generation algorithm itself, not requested directly. If too few words at this filter can be interlocked (minimum 3), returns a grid with insufficient=true instead of a 4xx — this is an expected, not exceptional, outcome of a narrow JLPT filter.
         */
        get: {
            parameters: {
                query: {
                    /** @description The JLPT level this practice session is centered on. */
                    jlpt_level: components["parameters"]["PracticeJlptLevelParam"];
                    /** @description "exact" — only jlpt_level. "and_below" — jlpt_level and every easier level (N5 is the floor, so N5 + and_below = N5 only). */
                    scope: components["parameters"]["PracticeScopeParam"];
                    /** @description "balanced" — as even a split as possible across every level in range. "challenge" — skewed toward the harder level(s) in range. */
                    distribution: components["parameters"]["PracticeDistributionParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A solved, interlocking crossword grid */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CrosswordGrid"];
                    };
                };
                /** @description Missing or expired access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sentences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List example sentences
         * @description Public endpoint. No auth required. Paginated, searchable by Japanese text.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (1-indexed) */
                    page?: components["parameters"]["PageParam"];
                    /** @description Number of results per page */
                    page_size?: components["parameters"]["PageSizeParam"];
                    /** @description Search within Japanese text (partial match) */
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of sentences */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedSentence"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sentences/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single sentence
         * @description Public endpoint. No auth required.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Tatoeba sentence ID
                     * @example 1234
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sentence detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sentence"];
                    };
                };
                /** @description Sentence not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all kanji components (radicals)
         * @description Public endpoint. No auth required.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (1-indexed) */
                    page?: components["parameters"]["PageParam"];
                    /** @description Number of results per page */
                    page_size?: components["parameters"]["PageSizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of components */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedComponent"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/components/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single component
         * @description Public endpoint. No auth required.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 1 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Component detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Component"];
                    };
                };
                /** @description Component not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reading/passages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List reading comprehension passages
         * @description Public endpoint. No auth required. Filterable by JLPT level. passage_text/furigana_segments/english_translation/questions are omitted here — fetch GET /reading/passages/{id} for full content.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (1-indexed) */
                    page?: components["parameters"]["PageParam"];
                    /** @description Number of results per page */
                    page_size?: components["parameters"]["PageSizeParam"];
                    jlpt_level?: "N5" | "N4" | "N3" | "N2" | "N1";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of passages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedReadingPassage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reading/passages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single passage with its questions
         * @description Requires auth. Fetches passage_text (and furigana_segments/ english_translation) from R2, and all questions for the passage ordered by question_order.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Passage detail including nested questions array */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadingPassage"];
                    };
                };
                /** @description Missing or expired access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Passage not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice/sentence-cloze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a sentence-cloze batch for a Practice tab session
         * @description Requires auth (Practice tab requires login). Shared game reachable from both the Kanji and Vocab Practice tabs. Each item is a real example sentence with the full target word blanked out (pre-marked with a "___" placeholder server-side) plus 4 options (the correct word and 3 same-JLPT-level distractor words).
         */
        get: {
            parameters: {
                query: {
                    /** @description Which entry point triggered this session. "kanji" sources target words from kanji at the requested level (via that kanji's vocabulary); "vocab" sources target words directly from vocab at the requested level. */
                    source: "kanji" | "vocab";
                    /** @description The JLPT level this practice session is centered on. */
                    jlpt_level: components["parameters"]["PracticeJlptLevelParam"];
                    /** @description "exact" — only jlpt_level. "and_below" — jlpt_level and every easier level (N5 is the floor, so N5 + and_below = N5 only). */
                    scope: components["parameters"]["PracticeScopeParam"];
                    /** @description "balanced" — as even a split as possible across every level in range. "challenge" — skewed toward the harder level(s) in range. */
                    distribution: components["parameters"]["PracticeDistributionParam"];
                    /** @description Number of items requested. The actual number returned may be lower if a level in range doesn't have enough rows (after exclude) to fill its share. */
                    count?: components["parameters"]["PracticeCountParam"];
                    /** @description Comma-separated list of identifiers (kanji characters, vocab ids, depending on the endpoint) already seen this session, so a top-up call doesn't reintroduce duplicates. */
                    exclude?: components["parameters"]["PracticeExcludeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A batch of sentence-cloze items for practice */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PracticeBatchCloze"];
                    };
                };
                /** @description Missing or expired access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get a presigned R2 upload URL
         * @description Requires auth. Validates size_bytes against MAX_FILE_SIZE_BYTES (10MB) and returns a presigned PUT URL plus the object_key to use. The client PUTs the file bytes directly to upload_url, then calls POST /files/confirm with the same object_key to record the metadata.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FilePresignInput"];
                };
            };
            responses: {
                /** @description Presigned upload URL generated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FilePresignResponse"];
                    };
                };
                /** @description Missing or expired access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description size_bytes exceeds MAX_FILE_SIZE_BYTES or validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm a completed upload and record file metadata
         * @description Requires auth. Called after the client has PUT the file bytes to upload_url. Writes the `files` row (object_key, filename, mime_type, size_bytes, uploaded_by) and returns it.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FileConfirmInput"];
                };
            };
            responses: {
                /** @description File metadata recorded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileMetadata"];
                    };
                };
                /** @description Missing or expired access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            /** @example not_found */
            error: string;
            /** @example Resource not found */
            message: string;
        };
        PaginatedKana: {
            data: components["schemas"]["Kana"][];
            /** @example 208 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
        };
        PaginatedKanji: {
            data: components["schemas"]["Kanji"][];
            /** @example 2200 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
        };
        PaginatedVocab: {
            data: components["schemas"]["Vocab"][];
            /** @example 10000 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
        };
        PaginatedSentence: {
            data: components["schemas"]["Sentence"][];
            /** @example 50000 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
        };
        PaginatedComponent: {
            data: components["schemas"]["Component"][];
            /** @example 253 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
        };
        RegisterInput: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example securepass123 */
            password: string;
        };
        LoginInput: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example securepass123 */
            password: string;
        };
        /** @description Returned on successful login or register. access_token is a short-lived JWT (15 min) — store in JS memory only. refresh_token is NOT in this response body. The server sets it as an HttpOnly cookie automatically. The client never sees or touches it. */
        AuthResponse: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            access_token: string;
            user: components["schemas"]["User"];
        };
        /** @description Returned on successful token refresh. New access_token — replace the one in memory. The refresh token cookie is automatically rotated by the server (new HttpOnly cookie set in the response). */
        RefreshResponse: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            access_token: string;
        };
        User: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00Z
             */
            created_at: string;
        };
        Kana: {
            /**
             * @description The kana character — also the primary key
             * @example き
             */
            character: string;
            /** @example ki */
            romaji: string;
            /**
             * @example hiragana
             * @enum {string}
             */
            type: "hiragana" | "katakana";
            /**
             * @description Chart row (consonant group). Derived at seed time from romaji + category. Null for yōon characters (きゃ etc.) and ん/ン.
             * @example k
             */
            row?: string | null;
            /**
             * @description Chart column (vowel). Derived at seed time from the last character of romaji. Null for yōon characters and ん/ン.
             * @example i
             */
            col?: string | null;
            /**
             * @example base
             * @enum {string}
             */
            category: "base" | "dakuten" | "handakuten" | "yoon";
            /**
             * @description For hiragana entries — the katakana version
             * @example キ
             */
            katakana_equivalent?: string | null;
            /**
             * @description For katakana entries — the hiragana version
             * @example き
             */
            hiragana_equivalent?: string | null;
            /** @example Looks like a key */
            mnemonic?: string | null;
            /**
             * Format: uri
             * @example https://r2.yourdomain.com/audio/kana/ki.mp3
             */
            audio_url?: string | null;
            /**
             * Format: uri
             * @example https://r2.yourdomain.com/kanjivg/kana/き.svg
             */
            stroke_order_svg_url?: string | null;
        };
        Component: {
            /** @example 1 */
            id: number;
            /** @example 木 */
            character: string;
            /**
             * @description Short English label used in mnemonic generation
             * @example tree
             */
            keyword: string;
            /** @example Tree or wood */
            meaning: string;
            /** @example 4 */
            stroke_count: number;
        };
        Kanji: {
            /**
             * @description The kanji character — also the primary key
             * @example 新
             */
            character: string;
            /**
             * @description Unicode codepoint hex — guaranteed present for all JLPT kanji
             * @example 065b0
             */
            unicode_hex: string;
            /**
             * @description English meanings — guaranteed present for all JLPT kanji
             * @example [
             *       "new",
             *       "neo-"
             *     ]
             */
            meanings: string[];
            /**
             * @description On'yomi readings — nullable, some kanji have only kun'yomi
             * @example [
             *       "シン"
             *     ]
             */
            onyomi?: string[] | null;
            /**
             * @description Kun'yomi readings — nullable, some kanji have only on'yomi
             * @example [
             *       "あたら.しい",
             *       "あら.た"
             *     ]
             */
            kunyomi?: string[] | null;
            /**
             * @description Name readings — nullable, only present for kanji used in names
             * @example [
             *       "あらた"
             *     ]
             */
            nanori?: string[] | null;
            /**
             * @description Nullable at insert time — overlaid from Tanos after initial KANJIDIC2 import
             * @example N2
             * @enum {string|null}
             */
            jlpt?: "N5" | "N4" | "N3" | "N2" | "N1" | null;
            /**
             * @description Japanese school grade (1–6 elementary, 8 secondary) — nullable, not all JLPT kanji have a school grade
             * @example 2
             */
            grade?: number | null;
            /**
             * @description Stroke count — guaranteed present for all JLPT kanji
             * @example 13
             */
            stroke_count: number;
            /**
             * @description Frequency rank out of 2500 most-used kanji
             * @example 56
             */
            frequency?: number | null;
            /**
             * @description Kangxi radical number from KANJIDIC2
             * @example 69
             */
            classical_radical_number?: number | null;
            /**
             * Format: uri
             * @example https://r2.yourdomain.com/kanjivg/065b0.svg
             */
            stroke_order_svg_url?: string | null;
            /**
             * @description LLM-generated default mnemonic
             * @example A person stands next to a tree and swings an axe — they're clearing land to build something NEW.
             */
            mnemonic?: string | null;
            /**
             * @description The authenticated user's personal mnemonic override. Null means the user has not written one — show mnemonic instead. Only present on GET /kanji/{character} (requires auth).
             * @example My new axe stands against the tree outside.
             */
            user_mnemonic?: string | null;
            /** @description Visual components this kanji is made of. Only included on GET /kanji/{character} (detail view). Not included in list responses for performance. */
            components?: components["schemas"]["Component"][] | null;
            /** @description Up to 10 example sentences, ordered by sentence ID (ascending). Only included on GET /kanji/{character}. Not included in list responses. */
            sentences?: components["schemas"]["Sentence"][] | null;
            /** @description Up to 20 vocabulary words that contain this kanji, ordered by JLPT level (N5 first, NULL last) then by is_common (common words first), then by vocab id as a stable tie-breaker. Grouped by reading_type on the frontend. Only included on GET /kanji/{character}. Not included in list responses. */
            vocab_words?: components["schemas"]["KanjiVocabEntry"][] | null;
            /** @description 3 plausible wrong-answer meanings, drawn from other kanji at the same JLPT level as this kanji (or other JLPT-less kanji, if this kanji has no jlpt). Combine with this kanji's own meanings to build a 4-option MCQ. Only included on GET /kanji/practice-batch. Null elsewhere. May contain fewer than 3 entries if the same-level pool is too small. */
            distractor_meanings?: string[] | null;
        };
        KanjiVocabEntry: {
            /**
             * @description JMdict entry sequence number
             * @example 1578850
             */
            id: string;
            /** @example 食べる */
            word: string;
            /** @example たべる */
            reading: string;
            /** @example taberu */
            romaji?: string | null;
            meanings: components["schemas"]["VocabMeaning"][];
            /**
             * @example N5
             * @enum {string|null}
             */
            jlpt?: "N5" | "N4" | "N3" | "N2" | "N1" | null;
            /** @description True if tagged ichi1/news1/spec1 in JMdict */
            is_common?: boolean | null;
            /**
             * @description Whether this vocab word uses the on'yomi or kun'yomi reading of the kanji. "on" = Chinese-origin compound reading (e.g. 食事 uses ショク). "kun" = Native Japanese reading (e.g. 食べる uses た). null = reading could not be resolved (irregular or single-char reading).
             * @enum {string|null}
             */
            reading_type?: "on" | "kun" | null;
        };
        MnemonicUpdateInput: {
            /**
             * @description The user's personal mnemonic. Send empty string "" to clear it and revert to the LLM default.
             * @example My new axe stands against the tree outside.
             */
            mnemonic: string;
        };
        MnemonicUpdateResponse: {
            /** @example 新 */
            character: string;
            /** @example My new axe stands against the tree outside. */
            user_mnemonic?: string | null;
        };
        VocabMeaning: {
            /**
             * @description Part of speech tags from JMdict
             * @example [
             *       "v1"
             *     ]
             */
            pos?: string[];
            /**
             * @example [
             *       "to eat",
             *       "to live on"
             *     ]
             */
            definitions?: string[];
        };
        FuriganaSegment: {
            /** @example 食 */
            ruby: string;
            /**
             * @description Reading for this segment. Null for kana-only segments.
             * @example た
             */
            rt?: string | null;
        };
        Vocab: {
            /**
             * @description JMdict entry sequence number
             * @example 1578850
             */
            id: string;
            /** @example 食べる */
            word: string;
            /** @example たべる */
            reading: string;
            /** @example taberu */
            romaji?: string | null;
            meanings: components["schemas"]["VocabMeaning"][];
            furigana?: components["schemas"]["FuriganaSegment"][] | null;
            /**
             * @example N5
             * @enum {string|null}
             */
            jlpt?: "N5" | "N4" | "N3" | "N2" | "N1" | null;
            /**
             * @description True if tagged ichi1/news1/spec1 in JMdict
             * @example true
             */
            is_common?: boolean | null;
            /** @description Up to 10 example sentences, ordered by sentence ID (ascending). Only included on GET /vocab/{id}. Not included in list responses. */
            sentences?: components["schemas"]["Sentence"][] | null;
            /** @description 3 plausible wrong-answer meanings, drawn from other vocab at the same JLPT level as this word (or other JLPT-less vocab, if this word has no jlpt). Combine with this word's own meanings to build a 4-option MCQ. Only included on GET /vocab/practice-batch. Null elsewhere. May contain fewer than 3 entries if the same-level pool is too small. */
            distractor_meanings?: string[] | null;
        };
        PracticeBatchKanji: {
            /** @description List-shape Kanji objects (no components/sentences/vocab_words/ user_mnemonic) plus distractor_meanings. */
            data: components["schemas"]["Kanji"][];
        };
        PracticeBatchVocab: {
            /** @description List-shape Vocab objects (sentences always null here) plus distractor_meanings. */
            data: components["schemas"]["Vocab"][];
        };
        PracticeClozeItem: {
            /**
             * @description The sentence with the target word replaced by a literal "___" placeholder (first occurrence only) — pre-marked server-side so the frontend never needs to search-and-replace the word itself.
             * @example 新しい___を買わなければならない。
             */
            sentence_japanese: string;
            /** @example I have to buy a new computer. */
            sentence_english: string;
            /**
             * @description The word that was removed from sentence_japanese.
             * @example パソコン
             */
            blanked_word: string;
            /**
             * @description 4 options including blanked_word, in randomized order. The other 3 are same-JLPT-level distractor words.
             * @example [
             *       "パソコン",
             *       "テレビ",
             *       "ラジオ",
             *       "カメラ"
             *     ]
             */
            options: string[];
        };
        PracticeBatchCloze: {
            data: components["schemas"]["PracticeClozeItem"][];
        };
        CrosswordCell: {
            /** @description 0-indexed row within this grid. */
            row: number;
            /** @description 0-indexed column within this grid. */
            col: number;
            /** @description True if this cell is not part of any word. */
            blocked: boolean;
            /** @description The kana at this cell. Null if blocked. */
            letter?: string | null;
            /** @description id(s), into the words array, of the word(s) occupying this cell. A cell where an across and a down word cross has two ids. Empty if blocked. */
            word_ids?: number[];
        };
        CrosswordWordEntry: {
            /** @description Referenced by CrosswordCell.word_ids. */
            id: number;
            /**
             * @description The correct kana sequence (this vocab word's reading).
             * @example がっこう
             */
            word: string;
            /**
             * @description English meaning (first definition) to display as the clue.
             * @example school
             */
            clue: string;
            /** @description 0-indexed start row. */
            row: number;
            /** @description 0-indexed start column. */
            col: number;
            /** @enum {string} */
            direction: "across" | "down";
        };
        CrosswordGrid: {
            /** @description True if there weren't enough mutually-interlocking words available at this JLPT filter to build a puzzle (minimum 3 words). When true, width/height are 0 and cells/words/decoy_kana are all empty — show a "not enough words at this level" state instead of a grid. */
            insufficient: boolean;
            width: number;
            height: number;
            /** @description One entry per (row, col) in the [0, width) x [0, height) bounding box. */
            cells: components["schemas"]["CrosswordCell"][];
            words: components["schemas"]["CrosswordWordEntry"][];
            /** @description Kana not needed by any answer in this grid, to mix into the picker bank so the puzzle isn't trivially solvable by elimination. */
            decoy_kana: string[];
        };
        FilePresignInput: {
            /** @example ki-mnemonic.png */
            filename: string;
            /** @example image/png */
            mime_type: string;
            /**
             * @description Must not exceed MAX_FILE_SIZE_BYTES (10MB).
             * @example 102400
             */
            size_bytes: number;
        };
        FilePresignResponse: {
            /**
             * @description Unique R2 object key. Pass this to POST /files/confirm.
             * @example uploads/3fae2b1e-2c2a-4b8a-9e0a-2a6a8b6e9c3e
             */
            object_key: string;
            /**
             * Format: uri
             * @description Presigned PUT URL. PUT the file bytes here directly.
             * @example https://<account>.r2.cloudflarestorage.com/<bucket>/uploads/3fae2b1e...?X-Amz-...
             */
            upload_url: string;
            /**
             * @description Seconds until upload_url expires.
             * @example 900
             */
            expires_in: number;
        };
        FileConfirmInput: {
            /**
             * @description The object_key returned by POST /files/presign.
             * @example uploads/3fae2b1e-2c2a-4b8a-9e0a-2a6a8b6e9c3e
             */
            object_key: string;
            /** @example ki-mnemonic.png */
            filename: string;
            /** @example image/png */
            mime_type: string;
            /** @example 102400 */
            size_bytes: number;
        };
        FileMetadata: {
            /**
             * Format: uuid
             * @example 7c9e6679-7425-40de-944b-e07fc1f90ae7
             */
            id: string;
            /** @example uploads/3fae2b1e-2c2a-4b8a-9e0a-2a6a8b6e9c3e */
            object_key: string;
            /** @example ki-mnemonic.png */
            filename: string;
            /** @example image/png */
            mime_type: string;
            /** @example 102400 */
            size_bytes: number;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            uploaded_by: string;
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00Z
             */
            created_at: string;
        };
        Sentence: {
            /**
             * @description Tatoeba sentence ID
             * @example 1234
             */
            id: number;
            /** @example 私は毎日学校に行きます。 */
            japanese: string;
            /** @example I go to school every day. */
            english: string;
        };
        ReadingQuestion: {
            /** @example 1 */
            id: number;
            /** @example 1 */
            passage_id: number;
            /** @example 1 */
            question_order: number;
            /** @example 田中さんはなぜ電話をしましたか。 */
            question_text: string;
            /**
             * @example [
             *       "パーティーに誘うため",
             *       "仕事の相談のため",
             *       "誕生日を伝えるため",
             *       "引っ越しの手伝いを頼むため"
             *     ]
             */
            options: string[];
            /** @example パーティーに誘うため */
            correct_answer: string;
            /** @example The passage states Tanaka-san called to invite the person to a party. */
            explanation: string;
        };
        ReadingPassage: {
            /** @example 1 */
            id: number;
            /** @example 田中さんのパーティー */
            title?: string | null;
            /**
             * @example N4
             * @enum {string}
             */
            jlpt_level: "N5" | "N4" | "N3" | "N2" | "N1";
            /**
             * Format: float
             * @description Raw jReadability score. Lower = harder (N1), higher = easier (N5).
             * @example 6.1
             */
            difficulty_score: number;
            /** @example 110 */
            word_count: number;
            /**
             * @example llm_qwen3.5
             * @enum {string}
             */
            source: "jaquad" | "jsquad" | "aozora" | "llm_qwen3.5";
            /**
             * @description Raw Japanese text, no furigana markup. Fetched from R2 at request time via content_key — never stored directly in Neon. Only included on GET /reading/passages/{id}; omitted from list responses to avoid an R2 fetch per row.
             * @example 来週の土曜日、田中さんから電話がありました。
             */
            passage_text?: string | null;
            /** @description Populated only for source=aozora. Null for all other sources — frontend falls back to client-side kuroshiro.js, same as sentences. Only included on GET /reading/passages/{id}. */
            furigana_segments?: components["schemas"]["FuriganaSegment"][] | null;
            /**
             * @description Only included on GET /reading/passages/{id}.
             * @example Last week I received a phone call from Tanaka-san.
             */
            english_translation?: string | null;
            /** @description All questions for this passage, ordered by question_order. Only included on GET /reading/passages/{id}. Not included in list responses. */
            questions?: components["schemas"]["ReadingQuestion"][] | null;
        };
        PaginatedReadingPassage: {
            data: components["schemas"]["ReadingPassage"][];
            /** @example 200 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
        };
        UserMnemonic: {
            /** @example 新 */
            character: string;
            /** @example My new axe stands against the tree outside. */
            user_mnemonic: string;
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00Z
             */
            updated_at: string;
        };
        PaginatedUserMnemonic: {
            data: components["schemas"]["UserMnemonic"][];
            /** @example 12 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
        };
    };
    responses: never;
    parameters: {
        /** @description Page number (1-indexed) */
        PageParam: number;
        /** @description Number of results per page */
        PageSizeParam: number;
        /** @description Optional. Filter to exactly this JLPT level. Mutually exclusive with jlpt_max — providing both is a 422. */
        JlptParam: "N5" | "N4" | "N3" | "N2" | "N1";
        /** @description Optional. Filter to this JLPT level or easier (e.g. N3 includes N3, N4, and N5; NULL-jlpt items are excluded). Mutually exclusive with jlpt — providing both is a 422. */
        JlptMaxParam: "N5" | "N4" | "N3" | "N2" | "N1";
        /** @description The JLPT level this practice session is centered on. */
        PracticeJlptLevelParam: "N5" | "N4" | "N3" | "N2" | "N1";
        /** @description "exact" — only jlpt_level. "and_below" — jlpt_level and every easier level (N5 is the floor, so N5 + and_below = N5 only). */
        PracticeScopeParam: "exact" | "and_below";
        /** @description "balanced" — as even a split as possible across every level in range. "challenge" — skewed toward the harder level(s) in range. */
        PracticeDistributionParam: "balanced" | "challenge";
        /** @description Number of items requested. The actual number returned may be lower if a level in range doesn't have enough rows (after exclude) to fill its share. */
        PracticeCountParam: number;
        /** @description Comma-separated list of identifiers (kanji characters, vocab ids, depending on the endpoint) already seen this session, so a top-up call doesn't reintroduce duplicates. */
        PracticeExcludeParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
