# generated by datamodel-codegen:
#   filename:  api-spec.yaml
#   timestamp: 2026-06-12T19:29:57+00:00

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, EmailStr, Field, constr


class ApiError(BaseModel):
    detail: str = Field(..., examples=['Not found'])
    code: str | None = Field(None, examples=['NOT_FOUND'])


class RegisterInput(BaseModel):
    email: EmailStr = Field(..., examples=['user@example.com'])
    password: constr(min_length=8) = Field(..., examples=['securepass123'])


class LoginInput(BaseModel):
    email: EmailStr = Field(..., examples=['user@example.com'])
    password: constr(min_length=8) = Field(..., examples=['securepass123'])


class RefreshResponse(BaseModel):
    access_token: str = Field(..., examples=['eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'])


class User(BaseModel):
    id: UUID = Field(..., examples=['550e8400-e29b-41d4-a716-446655440000'])
    email: EmailStr = Field(..., examples=['user@example.com'])
    created_at: AwareDatetime = Field(..., examples=['2026-01-01T00:00:00Z'])


class Type(Enum):
    hiragana = 'hiragana'
    katakana = 'katakana'


class Category(Enum):
    base = 'base'
    dakuten = 'dakuten'
    handakuten = 'handakuten'
    yoon = 'yoon'


class Kana(BaseModel):
    character: str = Field(
        ..., description='The kana character — also the primary key', examples=['き']
    )
    romaji: str = Field(..., examples=['ki'])
    type: Type = Field(..., examples=['hiragana'])
    row: str | None = Field(
        None,
        description='Chart row (consonant group). Derived at seed time from romaji + category. Null for yōon characters (きゃ etc.) and ん/ン.\n',
        examples=['k'],
    )
    col: str | None = Field(
        None,
        description='Chart column (vowel). Derived at seed time from the last character of romaji. Null for yōon characters and ん/ン.\n',
        examples=['i'],
    )
    category: Category = Field(..., examples=['base'])
    katakana_equivalent: str | None = Field(
        None, description='For hiragana entries — the katakana version', examples=['キ']
    )
    hiragana_equivalent: str | None = Field(
        None, description='For katakana entries — the hiragana version', examples=['き']
    )
    mnemonic: str | None = Field(None, examples=['Looks like a key'])
    audio_url: AnyUrl | None = Field(
        None, examples=['https://r2.yourdomain.com/audio/kana/ki.mp3']
    )
    stroke_order_svg_url: AnyUrl | None = Field(
        None, examples=['https://r2.yourdomain.com/kanjivg/kana/き.svg']
    )


class Component(BaseModel):
    id: int = Field(..., examples=[1])
    character: str = Field(..., examples=['木'])
    keyword: str = Field(
        ...,
        description='Short English label used in mnemonic generation',
        examples=['tree'],
    )
    meaning: str = Field(..., examples=['Tree or wood'])
    stroke_count: int = Field(..., examples=[4])


class Jlpt(Enum):
    N5 = 'N5'
    N4 = 'N4'
    N3 = 'N3'
    N2 = 'N2'
    N1 = 'N1'


class MnemonicUpdateInput(BaseModel):
    mnemonic: constr(min_length=0, max_length=500) = Field(
        ...,
        description='The user\'s personal mnemonic. Send empty string "" to clear it and revert to the LLM default.\n',
        examples=['My new axe stands against the tree outside.'],
    )


class MnemonicUpdateResponse(BaseModel):
    character: str = Field(..., examples=['新'])
    user_mnemonic: str = Field(
        ..., examples=['My new axe stands against the tree outside.']
    )


class VocabMeaning(BaseModel):
    pos: list[str] | None = Field(
        None, description='Part of speech tags from JMdict', examples=[['v1']]
    )
    definitions: list[str] | None = Field(None, examples=[['to eat', 'to live on']])


class FuriganaSegment(BaseModel):
    text: str = Field(..., examples=['食'])
    furigana: str | None = Field(
        None,
        description='Reading for this segment. Null for kana-only segments.',
        examples=['た'],
    )


class FilePresignInput(BaseModel):
    filename: str = Field(..., examples=['ki-mnemonic.png'])
    mime_type: str = Field(..., examples=['image/png'])
    size_bytes: int = Field(
        ...,
        description='Must not exceed MAX_FILE_SIZE_BYTES (10MB).',
        examples=[102400],
    )


class FilePresignResponse(BaseModel):
    object_key: str = Field(
        ...,
        description='Unique R2 object key. Pass this to POST /files/confirm.',
        examples=['uploads/3fae2b1e-2c2a-4b8a-9e0a-2a6a8b6e9c3e'],
    )
    upload_url: AnyUrl = Field(
        ...,
        description='Presigned PUT URL. PUT the file bytes here directly.',
        examples=[
            'https://<account>.r2.cloudflarestorage.com/<bucket>/uploads/3fae2b1e...?X-Amz-...'
        ],
    )
    expires_in: int = Field(
        ..., description='Seconds until upload_url expires.', examples=[900]
    )


class FileConfirmInput(BaseModel):
    object_key: str = Field(
        ...,
        description='The object_key returned by POST /files/presign.',
        examples=['uploads/3fae2b1e-2c2a-4b8a-9e0a-2a6a8b6e9c3e'],
    )
    filename: str = Field(..., examples=['ki-mnemonic.png'])
    mime_type: str = Field(..., examples=['image/png'])
    size_bytes: int = Field(..., examples=[102400])


class FileMetadata(BaseModel):
    id: UUID = Field(..., examples=['7c9e6679-7425-40de-944b-e07fc1f90ae7'])
    object_key: str = Field(
        ..., examples=['uploads/3fae2b1e-2c2a-4b8a-9e0a-2a6a8b6e9c3e']
    )
    filename: str = Field(..., examples=['ki-mnemonic.png'])
    mime_type: str = Field(..., examples=['image/png'])
    size_bytes: int = Field(..., examples=[102400])
    uploaded_by: UUID = Field(..., examples=['550e8400-e29b-41d4-a716-446655440000'])
    created_at: AwareDatetime = Field(..., examples=['2026-01-01T00:00:00Z'])


class Sentence(BaseModel):
    id: int = Field(..., description='Tatoeba sentence ID', examples=[1234])
    japanese: str = Field(..., examples=['私は毎日学校に行きます。'])
    english: str = Field(..., examples=['I go to school every day.'])
    jlpt: Jlpt | None = Field(None, examples=['N5'])
    source: str | None = Field('tatoeba', examples=['tatoeba'])


class PaginatedKana(BaseModel):
    data: list[Kana]
    total: int = Field(..., examples=[208])
    page: int = Field(..., examples=[1])
    page_size: int = Field(..., examples=[20])


class PaginatedSentence(BaseModel):
    data: list[Sentence]
    total: int = Field(..., examples=[50000])
    page: int = Field(..., examples=[1])
    page_size: int = Field(..., examples=[20])


class PaginatedComponent(BaseModel):
    data: list[Component]
    total: int = Field(..., examples=[253])
    page: int = Field(..., examples=[1])
    page_size: int = Field(..., examples=[20])


class AuthResponse(BaseModel):
    access_token: str = Field(..., examples=['eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'])
    user: User


class Kanji(BaseModel):
    character: str = Field(
        ..., description='The kanji character — also the primary key', examples=['新']
    )
    unicode_hex: str = Field(
        ...,
        description='Unicode codepoint hex — guaranteed present for all JLPT kanji',
        examples=['065b0'],
    )
    meanings: list[str] = Field(
        ...,
        description='English meanings — guaranteed present for all JLPT kanji',
        examples=[['new', 'neo-']],
    )
    onyomi: list[str] | None = Field(
        None,
        description="On'yomi readings — nullable, some kanji have only kun'yomi",
        examples=[['シン']],
    )
    kunyomi: list[str] | None = Field(
        None,
        description="Kun'yomi readings — nullable, some kanji have only on'yomi",
        examples=[['あたら.しい', 'あら.た']],
    )
    nanori: list[str] | None = Field(
        None,
        description='Name readings — nullable, only present for kanji used in names',
        examples=[['あらた']],
    )
    jlpt: Jlpt | None = Field(
        None,
        description='Nullable at insert time — overlaid from Tanos after initial KANJIDIC2 import',
        examples=['N2'],
    )
    grade: int | None = Field(
        None,
        description='Japanese school grade (1–6 elementary, 8 secondary) — nullable, not all JLPT kanji have a school grade',
        examples=[2],
    )
    stroke_count: int = Field(
        ...,
        description='Stroke count — guaranteed present for all JLPT kanji',
        examples=[13],
    )
    frequency: int | None = Field(
        None, description='Frequency rank out of 2500 most-used kanji', examples=[56]
    )
    classical_radical_number: int | None = Field(
        None, description='Kangxi radical number from KANJIDIC2', examples=[69]
    )
    classical_radical_char: str | None = Field(
        None, description='The actual radical character', examples=['斤']
    )
    stroke_order_svg_url: AnyUrl | None = Field(
        None, examples=['https://r2.yourdomain.com/kanjivg/065b0.svg']
    )
    mnemonic: str | None = Field(
        None,
        description='LLM-generated default mnemonic',
        examples=[
            "A person stands next to a tree and swings an axe — they're clearing land to build something NEW.\n"
        ],
    )
    user_mnemonic: str | None = Field(
        None,
        description="The authenticated user's personal mnemonic override. Null means the user has not written one — show mnemonic instead. Only present on GET /kanji/{character} (requires auth).\n",
        examples=['My new axe stands against the tree outside.'],
    )
    components: list[Component] | None = Field(
        None,
        description='Visual components this kanji is made of. Only included on GET /kanji/{character} (detail view). Not included in list responses for performance.\n',
    )
    sentences: list[Sentence] | None = Field(
        None,
        description='Example sentences containing this kanji. Only included on GET /kanji/{character} (detail view). Not included in list responses.\n',
    )


class Vocab(BaseModel):
    id: str = Field(
        ..., description='JMdict entry sequence number', examples=['1578850']
    )
    word: str = Field(..., examples=['食べる'])
    reading: str = Field(..., examples=['たべる'])
    romaji: str | None = Field(None, examples=['taberu'])
    meanings: list[VocabMeaning]
    furigana: list[FuriganaSegment] | None = None
    jlpt: Jlpt | None = Field(None, examples=['N5'])
    is_common: bool | None = Field(
        None, description='True if tagged ichi1/news1/spec1 in JMdict', examples=[True]
    )
    tags: dict[str, Any] | None = Field(
        None,
        description='JMdict dialect, field, and misc tags',
        examples=[{'dialect': 'kansai', 'field': 'medicine'}],
    )
    sentences: list[Sentence] | None = Field(
        None,
        description='Example sentences for this word. Only included on GET /vocab/{id} (detail view). Not included in list responses.\n',
    )


class PaginatedKanji(BaseModel):
    data: list[Kanji]
    total: int = Field(..., examples=[2200])
    page: int = Field(..., examples=[1])
    page_size: int = Field(..., examples=[20])


class PaginatedVocab(BaseModel):
    data: list[Vocab]
    total: int = Field(..., examples=[10000])
    page: int = Field(..., examples=[1])
    page_size: int = Field(..., examples=[20])
