# generated by datamodel-codegen:
#   filename:  api-spec.yaml
#   timestamp: 2026-06-20T23:54:31+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, EmailStr, Field


class ApiError(BaseModel):
    error: Annotated[str, Field(examples=['not_found'])]
    message: Annotated[str, Field(examples=['Resource not found'])]


class RegisterInput(BaseModel):
    email: Annotated[EmailStr, Field(examples=['user@example.com'])]
    password: Annotated[str, Field(examples=['securepass123'], min_length=8)]


class LoginInput(BaseModel):
    email: Annotated[EmailStr, Field(examples=['user@example.com'])]
    password: Annotated[str, Field(examples=['securepass123'], min_length=8)]


class RefreshResponse(BaseModel):
    access_token: Annotated[
        str, Field(examples=['eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'])
    ]


class User(BaseModel):
    id: Annotated[UUID, Field(examples=['550e8400-e29b-41d4-a716-446655440000'])]
    email: Annotated[EmailStr, Field(examples=['user@example.com'])]
    created_at: Annotated[AwareDatetime, Field(examples=['2026-01-01T00:00:00Z'])]


class Type(StrEnum):
    hiragana = 'hiragana'
    katakana = 'katakana'


class Category(StrEnum):
    base = 'base'
    dakuten = 'dakuten'
    handakuten = 'handakuten'
    yoon = 'yoon'


class Kana(BaseModel):
    character: Annotated[
        str,
        Field(description='The kana character — also the primary key', examples=['き']),
    ]
    romaji: Annotated[str, Field(examples=['ki'])]
    type: Annotated[Type, Field(examples=['hiragana'])]
    row: Annotated[
        str | None,
        Field(
            description='Chart row (consonant group). Derived at seed time from romaji + category. Null for yōon characters (きゃ etc.) and ん/ン.\n',
            examples=['k'],
        ),
    ] = None
    col: Annotated[
        str | None,
        Field(
            description='Chart column (vowel). Derived at seed time from the last character of romaji. Null for yōon characters and ん/ン.\n',
            examples=['i'],
        ),
    ] = None
    category: Annotated[Category, Field(examples=['base'])]
    katakana_equivalent: Annotated[
        str | None,
        Field(
            description='For hiragana entries — the katakana version', examples=['キ']
        ),
    ] = None
    hiragana_equivalent: Annotated[
        str | None,
        Field(
            description='For katakana entries — the hiragana version', examples=['き']
        ),
    ] = None
    mnemonic: Annotated[str | None, Field(examples=['Looks like a key'])] = None
    audio_url: Annotated[
        AnyUrl | None, Field(examples=['https://r2.yourdomain.com/audio/kana/ki.mp3'])
    ] = None
    stroke_order_svg_url: Annotated[
        AnyUrl | None, Field(examples=['https://r2.yourdomain.com/kanjivg/kana/き.svg'])
    ] = None


class Component(BaseModel):
    id: Annotated[int, Field(examples=[1])]
    character: Annotated[str, Field(examples=['木'])]
    keyword: Annotated[
        str,
        Field(
            description='Short English label used in mnemonic generation',
            examples=['tree'],
        ),
    ]
    meaning: Annotated[str, Field(examples=['Tree or wood'])]
    stroke_count: Annotated[int, Field(examples=[4])]


class Jlpt(StrEnum):
    N5 = 'N5'
    N4 = 'N4'
    N3 = 'N3'
    N2 = 'N2'
    N1 = 'N1'


class ReadingType(StrEnum):
    on = 'on'
    kun = 'kun'


class MnemonicUpdateInput(BaseModel):
    mnemonic: Annotated[
        str,
        Field(
            description='The user\'s personal mnemonic. Send empty string "" to clear it and revert to the LLM default.\n',
            examples=['My new axe stands against the tree outside.'],
            max_length=500,
            min_length=0,
        ),
    ]


class MnemonicUpdateResponse(BaseModel):
    character: Annotated[str, Field(examples=['新'])]
    user_mnemonic: Annotated[
        str | None, Field(examples=['My new axe stands against the tree outside.'])
    ] = None


class VocabMeaning(BaseModel):
    pos: Annotated[
        list[str] | None,
        Field(description='Part of speech tags from JMdict', examples=[['v1']]),
    ] = None
    definitions: Annotated[
        list[str] | None, Field(examples=[['to eat', 'to live on']])
    ] = None


class FuriganaSegment(BaseModel):
    ruby: Annotated[str, Field(examples=['食'])]
    rt: Annotated[
        str | None,
        Field(
            description='Reading for this segment. Null for kana-only segments.',
            examples=['た'],
        ),
    ] = None


class PracticeClozeItem(BaseModel):
    sentence_japanese: Annotated[
        str,
        Field(
            description='The sentence with the target word replaced by a literal "___" placeholder (first occurrence only) — pre-marked server-side so the frontend never needs to search-and-replace the word itself.\n',
            examples=['新しい___を買わなければならない。'],
        ),
    ]
    sentence_english: Annotated[str, Field(examples=['I have to buy a new computer.'])]
    blanked_word: Annotated[
        str,
        Field(
            description='The word that was removed from sentence_japanese.',
            examples=['パソコン'],
        ),
    ]
    options: Annotated[
        list[str],
        Field(
            description='4 options including blanked_word, in randomized order. The other 3 are same-JLPT-level distractor words.\n',
            examples=[['パソコン', 'テレビ', 'ラジオ', 'カメラ']],
            max_length=4,
            min_length=4,
        ),
    ]


class PracticeBatchCloze(BaseModel):
    data: list[PracticeClozeItem]


class FilePresignInput(BaseModel):
    filename: Annotated[str, Field(examples=['ki-mnemonic.png'])]
    mime_type: Annotated[str, Field(examples=['image/png'])]
    size_bytes: Annotated[
        int,
        Field(
            description='Must not exceed MAX_FILE_SIZE_BYTES (10MB).', examples=[102400]
        ),
    ]


class FilePresignResponse(BaseModel):
    object_key: Annotated[
        str,
        Field(
            description='Unique R2 object key. Pass this to POST /files/confirm.',
            examples=['uploads/3fae2b1e-2c2a-4b8a-9e0a-2a6a8b6e9c3e'],
        ),
    ]
    upload_url: Annotated[
        AnyUrl,
        Field(
            description='Presigned PUT URL. PUT the file bytes here directly.',
            examples=[
                'https://<account>.r2.cloudflarestorage.com/<bucket>/uploads/3fae2b1e...?X-Amz-...'
            ],
        ),
    ]
    expires_in: Annotated[
        int, Field(description='Seconds until upload_url expires.', examples=[900])
    ]


class FileConfirmInput(BaseModel):
    object_key: Annotated[
        str,
        Field(
            description='The object_key returned by POST /files/presign.',
            examples=['uploads/3fae2b1e-2c2a-4b8a-9e0a-2a6a8b6e9c3e'],
        ),
    ]
    filename: Annotated[str, Field(examples=['ki-mnemonic.png'])]
    mime_type: Annotated[str, Field(examples=['image/png'])]
    size_bytes: Annotated[int, Field(examples=[102400])]


class FileMetadata(BaseModel):
    id: Annotated[UUID, Field(examples=['7c9e6679-7425-40de-944b-e07fc1f90ae7'])]
    object_key: Annotated[
        str, Field(examples=['uploads/3fae2b1e-2c2a-4b8a-9e0a-2a6a8b6e9c3e'])
    ]
    filename: Annotated[str, Field(examples=['ki-mnemonic.png'])]
    mime_type: Annotated[str, Field(examples=['image/png'])]
    size_bytes: Annotated[int, Field(examples=[102400])]
    uploaded_by: Annotated[
        UUID, Field(examples=['550e8400-e29b-41d4-a716-446655440000'])
    ]
    created_at: Annotated[AwareDatetime, Field(examples=['2026-01-01T00:00:00Z'])]


class Sentence(BaseModel):
    id: Annotated[int, Field(description='Tatoeba sentence ID', examples=[1234])]
    japanese: Annotated[str, Field(examples=['私は毎日学校に行きます。'])]
    english: Annotated[str, Field(examples=['I go to school every day.'])]


class ReadingQuestion(BaseModel):
    id: Annotated[int, Field(examples=[1])]
    passage_id: Annotated[int, Field(examples=[1])]
    question_order: Annotated[int, Field(examples=[1])]
    question_text: Annotated[str, Field(examples=['田中さんはなぜ電話をしましたか。'])]
    options: Annotated[
        list[str],
        Field(
            examples=[
                [
                    'パーティーに誘うため',
                    '仕事の相談のため',
                    '誕生日を伝えるため',
                    '引っ越しの手伝いを頼むため',
                ]
            ],
            max_length=4,
            min_length=4,
        ),
    ]
    correct_answer: Annotated[str, Field(examples=['パーティーに誘うため'])]
    explanation: Annotated[
        str,
        Field(
            examples=[
                'The passage states Tanaka-san called to invite the person to a party.'
            ]
        ),
    ]


class JlptLevel(StrEnum):
    N5 = 'N5'
    N4 = 'N4'
    N3 = 'N3'
    N2 = 'N2'
    N1 = 'N1'


class Source(StrEnum):
    jaquad = 'jaquad'
    jsquad = 'jsquad'
    aozora = 'aozora'
    llm_qwen3_5 = 'llm_qwen3.5'


class ReadingPassage(BaseModel):
    id: Annotated[int, Field(examples=[1])]
    title: Annotated[str | None, Field(examples=['田中さんのパーティー'])] = None
    jlpt_level: Annotated[JlptLevel, Field(examples=['N4'])]
    difficulty_score: Annotated[
        float,
        Field(
            description='Raw jReadability score. Lower = harder (N1), higher = easier (N5).',
            examples=[6.1],
        ),
    ]
    word_count: Annotated[int, Field(examples=[110])]
    source: Annotated[Source, Field(examples=['llm_qwen3.5'])]
    passage_text: Annotated[
        str | None,
        Field(
            description='Raw Japanese text, no furigana markup. Fetched from R2 at request time via content_key — never stored directly in Neon. Only included on GET /reading/passages/{id}; omitted from list responses to avoid an R2 fetch per row.\n',
            examples=['来週の土曜日、田中さんから電話がありました。'],
        ),
    ] = None
    furigana_segments: Annotated[
        list[FuriganaSegment] | None,
        Field(
            description='Populated only for source=aozora. Null for all other sources — frontend falls back to client-side kuroshiro.js, same as sentences. Only included on GET /reading/passages/{id}.\n'
        ),
    ] = None
    english_translation: Annotated[
        str | None,
        Field(
            description='Only included on GET /reading/passages/{id}.',
            examples=['Last week I received a phone call from Tanaka-san.'],
        ),
    ] = None
    questions: Annotated[
        list[ReadingQuestion] | None,
        Field(
            description='All questions for this passage, ordered by question_order. Only included on GET /reading/passages/{id}. Not included in list responses.\n'
        ),
    ] = None


class PaginatedReadingPassage(BaseModel):
    data: list[ReadingPassage]
    total: Annotated[int, Field(examples=[200])]
    page: Annotated[int, Field(examples=[1])]
    page_size: Annotated[int, Field(examples=[20])]


class UserMnemonic(BaseModel):
    character: Annotated[str, Field(examples=['新'])]
    user_mnemonic: Annotated[
        str, Field(examples=['My new axe stands against the tree outside.'])
    ]
    updated_at: Annotated[AwareDatetime, Field(examples=['2026-01-01T00:00:00Z'])]


class PaginatedUserMnemonic(BaseModel):
    data: list[UserMnemonic]
    total: Annotated[int, Field(examples=[12])]
    page: Annotated[int, Field(examples=[1])]
    page_size: Annotated[int, Field(examples=[20])]


class PaginatedKana(BaseModel):
    data: list[Kana]
    total: Annotated[int, Field(examples=[208])]
    page: Annotated[int, Field(examples=[1])]
    page_size: Annotated[int, Field(examples=[20])]


class PaginatedSentence(BaseModel):
    data: list[Sentence]
    total: Annotated[int, Field(examples=[50000])]
    page: Annotated[int, Field(examples=[1])]
    page_size: Annotated[int, Field(examples=[20])]


class PaginatedComponent(BaseModel):
    data: list[Component]
    total: Annotated[int, Field(examples=[253])]
    page: Annotated[int, Field(examples=[1])]
    page_size: Annotated[int, Field(examples=[20])]


class AuthResponse(BaseModel):
    access_token: Annotated[
        str, Field(examples=['eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'])
    ]
    user: User


class KanjiVocabEntry(BaseModel):
    id: Annotated[
        str, Field(description='JMdict entry sequence number', examples=['1578850'])
    ]
    word: Annotated[str, Field(examples=['食べる'])]
    reading: Annotated[str, Field(examples=['たべる'])]
    romaji: Annotated[str | None, Field(examples=['taberu'])] = None
    meanings: list[VocabMeaning]
    jlpt: Annotated[Jlpt | None, Field(examples=['N5'])] = None
    is_common: Annotated[
        bool | None, Field(description='True if tagged ichi1/news1/spec1 in JMdict')
    ] = None
    reading_type: Annotated[
        ReadingType | None,
        Field(
            description='Whether this vocab word uses the on\'yomi or kun\'yomi reading of the kanji. "on" = Chinese-origin compound reading (e.g. 食事 uses ショク). "kun" = Native Japanese reading (e.g. 食べる uses た). null = reading could not be resolved (irregular or single-char reading).\n'
        ),
    ] = None


class Vocab(BaseModel):
    id: Annotated[
        str, Field(description='JMdict entry sequence number', examples=['1578850'])
    ]
    word: Annotated[str, Field(examples=['食べる'])]
    reading: Annotated[str, Field(examples=['たべる'])]
    romaji: Annotated[str | None, Field(examples=['taberu'])] = None
    meanings: list[VocabMeaning]
    furigana: list[FuriganaSegment] | None = None
    jlpt: Annotated[Jlpt | None, Field(examples=['N5'])] = None
    is_common: Annotated[
        bool | None,
        Field(
            description='True if tagged ichi1/news1/spec1 in JMdict', examples=[True]
        ),
    ] = None
    sentences: Annotated[
        list[Sentence] | None,
        Field(
            description='Up to 10 example sentences, ordered by sentence ID (ascending). Only included on GET /vocab/{id}. Not included in list responses.\n',
            max_length=10,
        ),
    ] = None
    distractor_meanings: Annotated[
        list[str] | None,
        Field(
            description="3 plausible wrong-answer meanings, drawn from other vocab at the same JLPT level as this word (or other JLPT-less vocab, if this word has no jlpt). Combine with this word's own meanings to build a 4-option MCQ. Only included on GET /vocab/practice-batch. Null elsewhere. May contain fewer than 3 entries if the same-level pool is too small.\n",
            max_length=3,
            min_length=3,
        ),
    ] = None


class PracticeBatchVocab(BaseModel):
    data: Annotated[
        list[Vocab],
        Field(
            description='List-shape Vocab objects (sentences always null here) plus distractor_meanings.\n'
        ),
    ]


class PaginatedVocab(BaseModel):
    data: list[Vocab]
    total: Annotated[int, Field(examples=[10000])]
    page: Annotated[int, Field(examples=[1])]
    page_size: Annotated[int, Field(examples=[20])]


class Kanji(BaseModel):
    character: Annotated[
        str,
        Field(
            description='The kanji character — also the primary key', examples=['新']
        ),
    ]
    unicode_hex: Annotated[
        str,
        Field(
            description='Unicode codepoint hex — guaranteed present for all JLPT kanji',
            examples=['065b0'],
        ),
    ]
    meanings: Annotated[
        list[str],
        Field(
            description='English meanings — guaranteed present for all JLPT kanji',
            examples=[['new', 'neo-']],
        ),
    ]
    onyomi: Annotated[
        list[str] | None,
        Field(
            description="On'yomi readings — nullable, some kanji have only kun'yomi",
            examples=[['シン']],
        ),
    ] = None
    kunyomi: Annotated[
        list[str] | None,
        Field(
            description="Kun'yomi readings — nullable, some kanji have only on'yomi",
            examples=[['あたら.しい', 'あら.た']],
        ),
    ] = None
    nanori: Annotated[
        list[str] | None,
        Field(
            description='Name readings — nullable, only present for kanji used in names',
            examples=[['あらた']],
        ),
    ] = None
    jlpt: Annotated[
        Jlpt | None,
        Field(
            description='Nullable at insert time — overlaid from Tanos after initial KANJIDIC2 import',
            examples=['N2'],
        ),
    ] = None
    grade: Annotated[
        int | None,
        Field(
            description='Japanese school grade (1–6 elementary, 8 secondary) — nullable, not all JLPT kanji have a school grade',
            examples=[2],
        ),
    ] = None
    stroke_count: Annotated[
        int,
        Field(
            description='Stroke count — guaranteed present for all JLPT kanji',
            examples=[13],
        ),
    ]
    frequency: Annotated[
        int | None,
        Field(description='Frequency rank out of 2500 most-used kanji', examples=[56]),
    ] = None
    classical_radical_number: Annotated[
        int | None,
        Field(description='Kangxi radical number from KANJIDIC2', examples=[69]),
    ] = None
    stroke_order_svg_url: Annotated[
        AnyUrl | None, Field(examples=['https://r2.yourdomain.com/kanjivg/065b0.svg'])
    ] = None
    mnemonic: Annotated[
        str | None,
        Field(
            description='LLM-generated default mnemonic',
            examples=[
                "A person stands next to a tree and swings an axe — they're clearing land to build something NEW.\n"
            ],
        ),
    ] = None
    user_mnemonic: Annotated[
        str | None,
        Field(
            description="The authenticated user's personal mnemonic override. Null means the user has not written one — show mnemonic instead. Only present on GET /kanji/{character} (requires auth).\n",
            examples=['My new axe stands against the tree outside.'],
        ),
    ] = None
    components: Annotated[
        list[Component] | None,
        Field(
            description='Visual components this kanji is made of. Only included on GET /kanji/{character} (detail view). Not included in list responses for performance.\n'
        ),
    ] = None
    sentences: Annotated[
        list[Sentence] | None,
        Field(
            description='Up to 10 example sentences, ordered by sentence ID (ascending). Only included on GET /kanji/{character}. Not included in list responses.\n',
            max_length=10,
        ),
    ] = None
    vocab_words: Annotated[
        list[KanjiVocabEntry] | None,
        Field(
            description='Up to 20 vocabulary words that contain this kanji, ordered by JLPT level (N5 first, NULL last) then by is_common (common words first), then by vocab id as a stable tie-breaker. Grouped by reading_type on the frontend. Only included on GET /kanji/{character}. Not included in list responses.\n',
            max_length=20,
        ),
    ] = None
    distractor_meanings: Annotated[
        list[str] | None,
        Field(
            description="3 plausible wrong-answer meanings, drawn from other kanji at the same JLPT level as this kanji (or other JLPT-less kanji, if this kanji has no jlpt). Combine with this kanji's own meanings to build a 4-option MCQ. Only included on GET /kanji/practice-batch. Null elsewhere. May contain fewer than 3 entries if the same-level pool is too small.\n",
            max_length=3,
            min_length=3,
        ),
    ] = None


class PracticeBatchKanji(BaseModel):
    data: Annotated[
        list[Kanji],
        Field(
            description='List-shape Kanji objects (no components/sentences/vocab_words/ user_mnemonic) plus distractor_meanings.\n'
        ),
    ]


class PaginatedKanji(BaseModel):
    data: list[Kanji]
    total: Annotated[int, Field(examples=[2200])]
    page: Annotated[int, Field(examples=[1])]
    page_size: Annotated[int, Field(examples=[20])]
