"""add_audio_url_columns

Revision ID: 82fd3377c68c
Revises: aad206f5eacd
Create Date: 2026-06-07 14:21:44.036852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82fd3377c68c'
down_revision: Union[str, Sequence[str], None] = 'aad206f5eacd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kanji', sa.Column('onyomi_audio_url', sa.Text(), nullable=True))
    op.add_column('kanji', sa.Column('kunyomi_audio_url', sa.Text(), nullable=True))
    op.add_column('sentences', sa.Column('audio_url', sa.Text(), nullable=True))
    op.add_column('vocab', sa.Column('audio_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocab', 'audio_url')
    op.drop_column('sentences', 'audio_url')
    op.drop_column('kanji', 'kunyomi_audio_url')
    op.drop_column('kanji', 'onyomi_audio_url')
    # ### end Alembic commands ###
