"""initial schema

Revision ID: 9f63750fc12b
Revises: 
Create Date: 2026-06-06 00:27:33.241050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f63750fc12b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('meaning', sa.String(), nullable=False),
    sa.Column('stroke_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character')
    )
    op.create_table('kana',
    sa.Column('character', sa.String(), nullable=False),
    sa.Column('romaji', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('row', sa.String(), nullable=True),
    sa.Column('col', sa.String(), nullable=True),
    sa.Column('katakana_equivalent', sa.String(), nullable=True),
    sa.Column('hiragana_equivalent', sa.String(), nullable=True),
    sa.Column('mnemonic', sa.String(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('stroke_order_svg_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('character')
    )
    op.create_table('kanji',
    sa.Column('character', sa.String(), nullable=False),
    sa.Column('unicode_hex', sa.String(), nullable=False),
    sa.Column('meanings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('onyomi', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kunyomi', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nanori', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jlpt', sa.String(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('stroke_count', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('classical_radical_number', sa.Integer(), nullable=True),
    sa.Column('classical_radical_char', sa.String(), nullable=True),
    sa.Column('stroke_order_svg_url', sa.String(), nullable=True),
    sa.Column('mnemonic', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('character')
    )
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('japanese', sa.Text(), nullable=False),
    sa.Column('english', sa.Text(), nullable=False),
    sa.Column('jlpt', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vocab',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('reading', sa.String(), nullable=False),
    sa.Column('romaji', sa.String(), nullable=True),
    sa.Column('meanings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('furigana', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jlpt', sa.String(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('frequency_rank', sa.Integer(), nullable=True),
    sa.Column('pitch_accent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_common', sa.Boolean(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_table('kanji_component',
    sa.Column('kanji_char', sa.String(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['kanji_char'], ['kanji.character'], ),
    sa.PrimaryKeyConstraint('kanji_char', 'component_id')
    )
    op.create_table('kanji_sentence',
    sa.Column('kanji_char', sa.String(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kanji_char'], ['kanji.character'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('kanji_char', 'sentence_id')
    )
    op.create_table('kanji_vocab',
    sa.Column('kanji_char', sa.String(), nullable=False),
    sa.Column('vocab_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['kanji_char'], ['kanji.character'], ),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocab.id'], ),
    sa.PrimaryKeyConstraint('kanji_char', 'vocab_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('user_mnemonics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kanji_character', sa.String(), nullable=False),
    sa.Column('mnemonic', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kanji_character', name='uq_user_mnemonic')
    )
    op.create_table('vocab_sentence',
    sa.Column('vocab_id', sa.String(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocab.id'], ),
    sa.PrimaryKeyConstraint('vocab_id', 'sentence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocab_sentence')
    op.drop_table('user_mnemonics')
    op.drop_table('refresh_tokens')
    op.drop_table('kanji_vocab')
    op.drop_table('kanji_sentence')
    op.drop_table('kanji_component')
    op.drop_table('files')
    op.drop_table('vocab')
    op.drop_table('users')
    op.drop_table('sentences')
    op.drop_table('kanji')
    op.drop_table('kana')
    op.drop_table('components')
    # ### end Alembic commands ###
