"""drop frequency from vocab

Revision ID: aad206f5eacd
Revises: b10497541b86
Create Date: 2026-06-06 22:57:33.659601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad206f5eacd'
down_revision: Union[str, Sequence[str], None] = 'b10497541b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocab', 'frequency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocab', sa.Column('frequency', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
