"""add_reading_comprehension_tables

Revision ID: aeee3884bdea
Revises: f6a1b2c3d4e5
Create Date: 2026-06-17 22:52:20.734197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeee3884bdea'
down_revision: Union[str, Sequence[str], None] = 'f6a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_passages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('jlpt_level', sa.String(), nullable=False),
    sa.Column('difficulty_score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('content_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_key')
    )
    op.create_index(op.f('ix_reading_passages_jlpt_level'), 'reading_passages', ['jlpt_level'], unique=False)
    op.create_index(op.f('ix_reading_passages_source'), 'reading_passages', ['source'], unique=False)
    op.create_table('reading_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('content_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['passage_id'], ['reading_passages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_key')
    )
    # NOTE: autogenerate also detected a pre-existing drift (dropped index
    # ix_kanji_sentence_sentence_id) from an earlier DB Optimizations commit
    # that never got its own migration. Left untouched here — out of scope
    # for the reading comprehension feature, handle separately if needed.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_questions')
    op.drop_index(op.f('ix_reading_passages_source'), table_name='reading_passages')
    op.drop_index(op.f('ix_reading_passages_jlpt_level'), table_name='reading_passages')
    op.drop_table('reading_passages')
    # ### end Alembic commands ###
