"""add reading_typ to kanji_vocab

Revision ID: c17d67f66e28
Revises: f240ab37c3f6
Create Date: 2026-06-16 02:32:38.356657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c17d67f66e28'
down_revision: Union[str, Sequence[str], None] = 'f240ab37c3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kanji_vocab', sa.Column('reading_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kanji_vocab', 'reading_type')
    # ### end Alembic commands ###
