"""drop_sentences_jlpt

Revision ID: f240ab37c3f6
Revises: ae24edf9e5e3
Create Date: 2026-06-15 18:35:44.201621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f240ab37c3f6'
down_revision: Union[str, Sequence[str], None] = 'ae24edf9e5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentences', 'jlpt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentences', sa.Column('jlpt', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
