"""
Step 3c — LLM gap-fill for the 49 components not covered by japanese-radicals.csv.

These are KRADFILE-specific decomposition elements — stroke shapes, variant forms,
and characters used purely as visual components rather than traditional Kangxi radicals.
Keywords and meanings were generated by Claude Code in-session.

Run from apps/api/:
    uv run python scripts/extract/03_components_gapfill.py
"""

import os

import psycopg
from dotenv import load_dotenv

load_dotenv()
DB_URL = os.environ["DATABASE_URL"].replace("+asyncpg", "")

# (character, keyword, meaning)
GAP_FILL = [
    ("ノ",  "sweep",      "diagonal sweeping stroke"),
    ("｜",  "vertical",   "vertical stroke"),
    ("ハ",  "legs",       "two legs or wings spread apart"),
    ("マ",  "hook",       "hooked stroke, katakana-MA shape"),
    ("ユ",  "basin",      "basin or tub shape"),
    ("丷",  "horns",      "two short strokes, horns or crown dots"),
    ("乃",  "from",       "from, possessive particle shape"),
    ("九",  "nine",       "the number nine"),
    ("乞",  "beg",        "to beg or request"),
    ("ヨ",  "rake",       "rake or comb shape, three horizontal strokes"),
    ("久",  "long",       "long time, lasting"),
    ("也",  "also",       "also, classical copula particle"),
    ("亡",  "deceased",   "deceased, perish, flee"),
    ("及",  "reach",      "to reach, extend to"),
    ("尢",  "lame",       "lame, crooked-legged figure"),
    ("已",  "already",    "already, to stop, the sixth earthly branch"),
    ("幺",  "tiny",       "tiny, small; thread or infant"),
    ("彑",  "snout",      "pig's snout or head shape"),
    ("五",  "five",       "the number five"),
    ("井",  "well",       "water well, grid pattern"),
    ("元",  "origin",     "origin, beginning, foundation"),
    ("勿",  "not",        "do not, must not"),
    ("尤",  "especially", "especially, the most, fault"),
    ("屯",  "camp",       "camp, village, to assemble"),
    ("巴",  "coil",       "coil, comma-shape, the tomoe spiral pattern"),
    ("戸",  "door",       "door, household, family unit"),
    ("攵",  "strike",     "to strike or tap, simplified form of 攴"),
    ("王",  "king",       "king, ruler, sovereign"),
    ("⺲",  "net",        "net, variant form of 网"),
    ("世",  "world",      "world, generation, society"),
    ("冊",  "book",       "book, volume, bound tablets"),
    ("巨",  "giant",      "giant, huge, enormous"),
    ("母",  "mother",     "mother, female parent"),
    ("牙",  "fang",       "fang, tusk, tooth"),
    ("西",  "west",       "west, western direction"),
    ("麦",  "wheat",      "wheat, barley, grain"),
    ("免",  "exempt",     "to exempt, escape from, avoid"),
    ("奄",  "cover",      "to cover over, suddenly"),
    ("岡",  "hill",       "hill, ridge, high ground"),
    ("斉",  "equal",      "equal, adjusted, neat and uniform"),
    ("長",  "long",       "long, lengthy, chief or elder"),
    ("青",  "blue",       "blue, green, young and fresh"),
    ("品",  "goods",      "goods, article, quality, character"),
    ("竜",  "dragon",     "dragon, simplified form of 龍"),
    ("亀",  "turtle",     "turtle, tortoise"),
    ("啇",  "stalk",      "stalk, stem, root of a plant"),
    ("黄",  "yellow",     "yellow, the color yellow"),
    ("歯",  "tooth",      "tooth, teeth, dental"),
    ("無",  "nothing",    "nothing, nothingness, without"),
]


def main():
    print("Connecting to database ...")
    with psycopg.connect(DB_URL) as conn:
        with conn.cursor() as cursor:
            updated = 0
            skipped = 0

            for character, keyword, meaning in GAP_FILL:
                cursor.execute(
                    """
                    UPDATE components
                    SET keyword = %s, meaning = %s
                    WHERE character = %s AND meaning = '?'
                    """,
                    (keyword, meaning, character),
                )
                # Only count if the row actually had a placeholder — if it was
                # already filled by the CSV we leave it alone (WHERE meaning = '?')
                if cursor.rowcount > 0:
                    updated += 1
                else:
                    skipped += 1

            conn.commit()

            print(f"  Updated : {updated}")
            print(f"  Skipped (already filled by CSV): {skipped}")

            # Verify no placeholders remain
            cursor.execute("SELECT COUNT(*) FROM components WHERE meaning = '?'")
            remaining = (cursor.fetchone() or (0,))[0]
            if remaining == 0:
                print("  All components fully populated — no placeholders remain.")
            else:
                cursor.execute(
                    "SELECT character FROM components WHERE meaning = '?' ORDER BY stroke_count"
                )
                chars = [r[0] for r in cursor.fetchall()]
                print(f"  WARNING: {remaining} placeholders still remain: {chars}")


if __name__ == "__main__":
    main()
